#!/bin/bash

mvn clean install -Dmaven.test.skip -DskipTests=true -Dsource.skip
cp ./target/Fascia_Plugin-0.0.1.jar ~/Desktop/Fiji.app/plugins/

osascript -e 'quit app "Fiji.app"'
open /Users/alexis/Desktop/Fiji.app
